Repository adobecom/express, pull requests merged in 2023-12, with the labels that each got.

#511 Go Live
  express/scripts/utils.js
  express/sitemap-index.xml
Labels: do not merge

#522 [TemplateX] Remove Temporary Workaround for Akamai Cache Collision
  express/blocks/template-x/template-search-api-v3.js
Labels: attention needed

#519 [Experimentation] Finer Control over AEP Audience
  express/scripts/utils.js
Labels: attention needed

#388 Logged in user auto redirect to product
  express/features/direct-path-to-product/direct-path-to-product.css
  express/features/direct-path-to-product/direct-path-to-product.js
  express/scripts/delayed.js
Labels: attention needed

#525 [TemplateX] Add Fallback Strategy for Template Breadcrumbs Translation
  express/blocks/template-list/breadcrumbs.js
  express/blocks/template-x/breadcrumbs.js
Labels: enhancement, attention needed

#528 [PEP] Fix using loadStyle from loadCSS
  express/features/direct-path-to-product/direct-path-to-product.js
Labels: attention needed

#529 [PEP] Consolidate localStorage Keys
  express/features/direct-path-to-product/direct-path-to-product.js
Labels: attention needed

#531 [Mobile Beta][Benchmark-Gating] Fix Cookie Method
  express/scripts/mobile-beta-gating.js
Labels: attention needed
