Repository adobecom/express, pull requests merged in 2023-10, with the labels that each got.

#322 Analytics Remove Legacy and Spark
  express/scripts/instrument.js
Labels: enhancement

#379 Embed iframe loading in as text fix
  express/blocks/embed/embed.js
Labels: bug

#377 Template LH back to 90+
  express/scripts/content-replace.js
  express/scripts/scripts.js
  express/scripts/utils.js
Labels: enhancement

#374 Code logic consistency refactoring around decorateMain
  express/blocks/faas/faas.css
  express/blocks/fragment/fragment.js
  express/scripts/browse-api-controller.js
  express/scripts/utils.js
Labels: question, do not merge
