Repository adobecom/express, pull requests merged in 2024-01, with the labels that each got.

#546 Revert "QA guide checklist logging + story selector"
  express/scripts/features/qa-guide/qa-guide.css
  express/scripts/features/qa-guide/qa-guide.js
  express/scripts/features/qa-guide/utils/storage-controller.js
  express/scripts/utils/sidekick.js
Labels: attention needed

#549 [Beta-Gating] Mobile Beta-Gating Final Requirements
  express/scripts/mobile-beta-gating.js
  express/scripts/scripts.js
  express/scripts/utils.js
  test/unit/scripts/mobile-beta-gating.test.js
Labels: attention needed

#556 MWPW-140620 fix floating cta in experiments to be found in sheet
  express/scripts/utils.js
Labels: attention needed

#557 [MWPW-140776] - [Express mobile beta] SEO CTA adjustments to fit loc copy
  express/blocks/shared/floating-cta.css
  express/blocks/shared/floating-cta.js
Labels: attention needed

#550 [MWPW-140190-1] - Blog Visual Fixes (Issue #2 Remove free widget on blogs)
  express/blocks/columns/columns.js
Labels: attention needed

#562 [MWPW-140239] Milo tabs block import & styling
  express/blocks/tabs-ax/tabs-ax.css
  express/blocks/tabs-ax/tabs-ax.js
Labels: enhancement

#569 [MWPW-140776] - [Express mobile beta] SEO CTA adjustments to fit loc copy
  express/blocks/shared/floating-cta.css
  express/blocks/shared/floating-cta.js
Labels: attention needed

#580 [Mobile Beta] Update DenyList Logic
  express/scripts/mobile-beta-gating.js
  test/unit/scripts/mobile-beta-gating.test.js
Labels: do not merge

#588 MWPW-139776 | Cleaning up merch code logic
  express/blocks/merch/README.md
  express/blocks/merch/merch.css
  express/blocks/merch/merch.js
  express/scripts/utils.js
Labels: do not merge
