Repository adobecom/express, pull requests merged in 2024-09, with the labels that each got.

#1116 Changes Delimiter Token For Pricing Cards Credits
  express/blocks/pricing-cards-credits/pricing-cards-credits.js
  test/unit/blocks/pricing-cards-credits/mocks/body.html
Labels: ready for stage

#1112 [Marquee Logo Injection] Fullscreen Marquee + Columns + Headline
  express/blocks/columns/columns.css
  express/blocks/columns/columns.js
  express/blocks/fullscreen-marquee/fullscreen-marquee.css
  express/blocks/fullscreen-marquee/fullscreen-marquee.js
  express/blocks/headline/headline.css
  express/blocks/headline/headline.js
  express/blocks/susi-light/susi-light.js
Labels: ready for stage

#1133 Fix Template-X Toolbar Sticky behavior
  express/blocks/search-marquee/search-marquee.js
  express/blocks/template-x/template-x.css
Labels: attention needed

#1132 [AI Create Page] How to Cards Style Updates
  express/blocks/how-to-cards/how-to-cards.css
Labels: attention needed

#1142 [MWPW-158469] P0 Changes For Feature Compare Table
  express/blocks/pricing-table/pricing-table.css
  express/blocks/pricing-table/pricing-table.js
Labels: attention needed, ready for stage

#1134 [MWPW-158582] Authoring And CSS Enhancement For Interactive Marquee
  express/blocks/logo-row/logo-row.css
  express/blocks/logo-row/logo-row.js
  express/blocks/pricing-cards-credits/pricing-cards-credits.css
  express/blocks/wayfinder/wayfinder.css
  express/features/horizontal-masonry/horizontal-masonry.css
  express/features/horizontal-masonry/horizontal-masonry.js
  test/unit/blocks/interactive-marquee/mocks/body.html
Labels: attention needed

#1144 9/19 Release
  express/blocks/banner/banner.css
  express/blocks/banner/banner.js
  express/blocks/columns/columns.css
  express/blocks/columns/columns.js
  express/blocks/faq/faq.css
  express/blocks/faq/faq.js
  express/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/blocks/fullscreen-marquee/fullscreen-marquee.css
  express/blocks/fullscreen-marquee/fullscreen-marquee.js
  express/blocks/how-to-steps/how-to-steps.css
  express/blocks/how-to-steps/how-to-steps.js
  express/blocks/link-list/link-list.css
  express/blocks/link-list/link-list.js
  express/blocks/logo-row/logo-row.css
  express/blocks/logo-row/logo-row.js
  express/blocks/pricing-cards-credits/pricing-cards-credits.css
  express/blocks/pricing-table/pricing-table.css
  express/blocks/pricing-table/pricing-table.js
  express/blocks/promotion/promotion.css
  express/blocks/promotion/promotion.js
  express/blocks/template-x/template-x.css
  express/blocks/wayfinder/wayfinder.css
  express/features/horizontal-masonry/horizontal-masonry.css
  express/features/horizontal-masonry/horizontal-masonry.js
  express/icons/canva-icon-20.svg
  express/styles/styles.css
  test/unit/blocks/interactive-marquee/mocks/body.html
Labels: attention needed

#1141 [MWPW-158235] Simplified Pricing Cards
  express/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
  express/blocks/simplified-pricing-cards/simplified-pricing-tooltip.js
  test/unit/blocks/simplified-pricing-cards/mocks/body.html
  test/unit/blocks/simplified-pricing-cards/simplified-pricing-cards.test.js
Labels: ready for stage
