Repository adobecom/express, pull requests merged in 2024-07, with the labels that each got.

#1002 Upload Globe Icon for OPT-28193
  express/icons/SX_GlobeGrid_18_N.svg
Labels: attention needed, trivial

#1012 [Create Pages] [Pictures] Remove Unwanted Attributes
  express/blocks/fullscreen-marquee-desktop/fullscreen-marquee-desktop.js
  express/blocks/fullscreen-marquee/fullscreen-marquee.js
  express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
Labels: bug, attention needed

#999 [Branding] Search-Marquee Logo Injection
  express/blocks/search-marquee/search-marquee.css
  express/blocks/search-marquee/search-marquee.js
Labels: trivial

#1016 [Modal][Milo Migration] Sync Modal with Milo
  express/blocks/modal/modal.css
  express/blocks/modal/modal.js
  express/blocks/modal/modal.merch.js
  express/scripts/express-delayed.js
  express/scripts/utils/action.js
  express/styles/rounded-corners.css
Labels: attention needed

#1022 [Modal] Dedup Milo Modal Hashes
  express/blocks/modal/modal.js
Labels: attention needed

#1019 [Branch Links] Added Region along with Locale
  express/scripts/branchlinks.js
Labels: attention needed

#1028 [Personalization][RTP] Merge Marquee-exp-1 into Marquee Entitled Variant
  express/blocks/marquee/marquee.css
  express/blocks/marquee/marquee.js
Labels: attention needed

#1034 [BTS][SUSI-Light] ATC Triggers Redirect Directly to Destination if Already Signed in
  express/blocks/susi-light/susi-light.js
Labels: attention needed

#1033 Stage to Main (7/24)
  express/blocks/marquee/marquee.css
  express/blocks/marquee/marquee.js
  express/blocks/susi-light/susi-light.js
  express/scripts/utils.js
  express/styles/styles.css
Labels: attention needed

#1045 Add New Currencies
  express/scripts/utils/pricing.js
Labels: do not merge
