Repository adobecom/express, pull requests merged in 2024-04, with the labels that each got.

#811 [Mobile-GA][Deep-Linking] Add More Search Params
  express/scripts/instrument.js
Labels: attention needed

#803 [Mobile-GA][Template-X] Update Search Redirect
  express/blocks/search-marquee/search-marquee.js
  express/blocks/template-x/template-x.js
  express/scripts/content-replace.js
  express/scripts/template-redirect.js
Labels: attention needed

#829 [Mobile-GA] Added section metadata for no padding
  express/styles/styles.css
Labels: attention needed

#831 Template Placeholder Card Fix
  express/blocks/template-x/template-x.css
  express/blocks/template-x/template-x.js
Labels: attention needed

#827 Stage to Main 4/17
  express/styles/styles.css
  tools/sidekick/config.json
Labels: attention needed

#832 [MWPW-146707] Template Placeholder Icon Alignment Fix
  express/blocks/template-x/template-x.css
  express/blocks/template-x/template-x.js
Labels: enhancement

#813 [Floating-CTA][Performance] Replace Fetch with Metadata for FloatingCTAs
  express/blocks/bubble-ui-button/bubble-ui-button.js
  express/blocks/floating-button/floating-button.js
  express/blocks/multifunction-button/multifunction-button.js
  express/blocks/shared/floating-cta.css
  express/blocks/shared/floating-cta.js
  express/scripts/utils.js
  express/styles/styles.css
  test/unit/blocks/floating-button/mocks/body.html
Labels: require authoring first
